### PR TITLE
Added styles

### PR DESCRIPTION
**Pull request by hplehal**
Added styles CSS please check

### CODE REVIEW

**Comment by satv1r** [comment]
@hplehal Our Netlify setup is treating all warnings as errors (something to do with environment variables, check the logs). However, I don't think it actually breaks the app, so do you want me to accept this? I think it's fine if we accept this and just merge.

**Comment by hplehal** [comment]
Netlify is complaning because i didnt use popmovies and popbooks. let me fix it

**Comment by satv1r** [comment]
It’s complaining because it’s setting all warnings to be treated as errors. Maybe this is good to ensure that we don’t deploy something with bad practices.

We can keep it this way if you’d like.

**Comment by hplehal** [comment]
This works now :)

**Pull request merged**
